name: Build and Release

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: windows-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up MSVC (Visual Studio C++ Compiler)
        uses: ilammy/msvc-dev-cmd@v1 

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Copy SFML DLLs to Build Folder
        run: |
         
          copy *.dll build\Release\

      - name: Upload EXE and DLLs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YinPad
          path: |
            build/Release/YinPad.exe  
            build/Release/*.dll           

